// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1KMxVjV3YXaKb-zrE2gEagNAKjhZmE1I',
    appId: '1:755212646520:web:f520b1eefea5bc6a40558d',
    messagingSenderId: '755212646520',
    projectId: 'homeshop-8d710',
    authDomain: 'homeshop-8d710.firebaseapp.com',
    storageBucket: 'homeshop-8d710.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmLw_6PpJ4jvv7010TWL2oOsfClUZRa8A',
    appId: '1:755212646520:android:1ce785d6700bf41640558d',
    messagingSenderId: '755212646520',
    projectId: 'homeshop-8d710',
    storageBucket: 'homeshop-8d710.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZap74dycHtVlfdAn1hE-SMr-yHYgt1CU',
    appId: '1:755212646520:ios:b19c03fbc955449d40558d',
    messagingSenderId: '755212646520',
    projectId: 'homeshop-8d710',
    storageBucket: 'homeshop-8d710.appspot.com',
    iosClientId:
        '755212646520-64h4olrqtoph5kklophmms2ee52f4odp.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZap74dycHtVlfdAn1hE-SMr-yHYgt1CU',
    appId: '1:755212646520:ios:b19c03fbc955449d40558d',
    messagingSenderId: '755212646520',
    projectId: 'homeshop-8d710',
    storageBucket: 'homeshop-8d710.appspot.com',
    iosClientId:
        '755212646520-64h4olrqtoph5kklophmms2ee52f4odp.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeShop',
  );
}
